### ISSUE TITLE
Using audiojs/decibels

### ISSUE THREAD

**Issue by jamen** [audio-lab/gain#10]
I believe it was mentioned somewhere in #9 for using decibels.  [audiojs/decibels](https://github.com/audiojs/decibels) might do the trick?

**Comment by dy** [comment]
Oh, sweet, yeah, I used to use decibels package, it is nice. The only thing - it falls to 0 if db < -40, which sometimes is not expected.
We have to make `mode` I think. Or `units`.

**Comment by dy** [comment]
Yes, analyzed some sources: [1](https://dsp.stackexchange.com/questions/2990/how-to-change-volume-of-a-pcm-16-bit-signed-audio/2996#2996), [2](https://web.archive.org/web/20150923161151/http://www.ypass.net/blog/2010/01/pcm-audio-part-3-basic-audio-effects-volume-control/), [3](https://www.reddit.com/r/programming/comments/9n2y0/stop_making_linear_volume_controls/), [4](https://www.dr-lex.be/info-stuff/volumecontrols.html), [5](http://www.robotplanet.dk/audio/audio_gui_design/) − irresponsibly enough now we use tan-based homemade solution (the guy did not know math to set up logarithms). But opinions what volume control should be vary from `x²`, `x³` ... `x⁷` to `40db` range mapping (the latter I used in [latest audio commit](4ecd1992187e1088998e3123e7fc810770da2bd6)).
Should we consider list of modes or come up with single approach?

**Comment by jamen** [comment]
Awesome that is neat to learn.

I think we should set it up so we can use a single function that follows proper conventions those sources talk about, by using log that covers common use case.  (also in [that reddit post](https://www.reddit.com/r/programming/comments/9n2y0/stop_making_linear_volume_controls/) someone mentions [the sone scale](https://en.wikipedia.org/wiki/Sone) which looks interesting)

But we might also want to set it up so we have other functions for other modes, like `gain()`, `gain.sone()`, etc. but those are kind of second priority in my opinion.

**Comment by dy** [comment]
I am not sure about correctness of using sones for amplification: they use human hearing loudness curves, which would mean equalizing the signal to produce different loudness. Sones imply specifics of human hear, they don't reflect the property of sound itself.
